vich_uploader:
  db_driver: orm

  metadata:
    type: attribute

  mappings:
    artists:
      uri_prefix: /images/artists
      upload_destination: "%kernel.project_dir%/public/images/artists"
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
    pieces:
      uri_prefix: /images/pieces
      upload_destination: "%kernel.project_dir%/public/images/pieces"
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
