<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVYEGwPY\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVYEGwPY/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVYEGwPY.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVYEGwPY\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerVYEGwPY\App_KernelDevDebugContainer([
    'container.build_hash' => 'VYEGwPY',
    'container.build_id' => '134a1330',
    'container.build_time' => 1688717794,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVYEGwPY');
